spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:h2:mem:produto_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5671
    username: sodidwlr
    password: FTA1ydq61V7bM0mYoyF1aitGhjY0mHN_
    virtual-host: sodidwlr
    ssl:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8082

broker:
  exchange: pedidos.exchange
  queue:
    pedido-criado: pedido.criado
    estoque-atualizado: estoque.atualizado

##spring:
  ##application:
    ##name: produto-service
  ##datasource:
    ##url: jdbc:mysql://localhost:3306/produto_db
    ##username: admin
    ##password: root
  ##jpa:
    ##hibernate.ddl-auto: update
    ##show-sql: true